name: pytest

on:
  push:

jobs:
  flake8-pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.2.1]
        os: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: pdm-project/setup-pdm@v3 # https://github.com/pdm-project/setup-pdm
        name: Setup PDM
        with:
          # python-version: 3.9  # Version range or exact version of a Python version to use, the same as actions/setup-python
          architecture: x64    # The target architecture (x86, x64) of the Python interpreter. the same as actions/setup-python
          version: 2.4.7       # The version of PDM to install. Leave it as empty to use the latest version from PyPI, or 'head' to use the latest version from GitHub
          prerelease: true     # Allow prerelease versions to be installed
          enable-pep582: true  # Enable PEP 582 package loading globally
      - name: Install packages
        run: pdm install
      - name: Run flake8
        run: |
          pdm run flake8 baidu_sign --exit-zero
      - name: Run pytest
        run: pdm run pytest tests
